### PR TITLE
Closes #7

### LINKED ISSUE #7: Multicheckbox migration
I've got a migration that is mapping multi-checkbox fields to single checkbox fields. I'll submit a PR for this if/when I find the solution

### PR DESCRIPTION
**Pull request by dustinleblanc**

### CODE REVIEW

**Comment by chx** [comment]
This issue shows the clear inferiority of github: I have a different solution to this and there's no simple way to submit it properly. Oh well. I pasted a patch to https://gist.github.com/chx/f4849a6c3ab4b901eaf5e7b1a2eb2fda

**Comment by dustinleblanc** [comment]
You can actually submit a pr to my branch which is much simpler than the Drupal workflow IMO, you can also use the PR review system and Github now includes an inline method to suggest different code. I think more than anything you're just not used to Github @chx 😆

**Comment by chx** [comment]
But then I would need to base my commit on top of yours...?

**Comment by dustinleblanc** [comment]
Sure, or you could just open a new PR, reference the same issue #7 and the maintainer can just close a pr and accept one, or say no to both :laughing: Either way, the discussion of different methods can happen on the issue itself while the pull requests are simply patches that are less of a pain in the butt to generate, track, and merge.

**Comment by heshanlk** [comment]
This has already been added by the Drupal.org community.

**Pull request closed without merging**
